CREATE PROCEDURE [dbo].[Consumers_UPDATE]
(      
	--@ID NVARCHAR(100),
	--@Client NVARCHAR(100),
	@Server NVARCHAR(100),
	@Application NVARCHAR(100),	
	
	@HCCBAPP2 NVARCHAR(100),
	@HCCBAPP3 NVARCHAR(100),
	@HCCBAPP4 NVARCHAR(100),
	@HCCBAPP5 NVARCHAR(100),
	@HCCBAPP6 NVARCHAR(100),
	@SAASAPP4 NVARCHAR(100),
	@SAASAPP5 NVARCHAR(100),
	@SAASAPP6 NVARCHAR(100),
	@HCCBFAT NVARCHAR(100),
	@HCCBUAT NVARCHAR(100),
	@SAASSIT NVARCHAR(100),
	@SAASUAT NVARCHAR(100),
	@SITV2APP NVARCHAR(100),
	@UATV2APP NVARCHAR(100),
	@PRDV2APP1 NVARCHAR(100),
	@SAASPILOT NVARCHAR(100),
	@SAASDEMO NVARCHAR(100),
	@DEMOV2 NVARCHAR(100),
	@TRAINING NVARCHAR(100),
	@IsActive NVARCHAR(100)
)
AS
BEGIN
	SET NOCOUNT ON;  
	--SELECT * FROM CONSUMERS
	UPDATE C SET		
		 HCCBAPP2 = @HCCBAPP2,
		 HCCBAPP3 = @HCCBAPP3,
		 HCCBAPP4 = @HCCBAPP4,
		 HCCBAPP5 = @HCCBAPP5,
		 HCCBAPP6 = @HCCBAPP6,

		 SAASAPP4 = @SAASAPP4,
		 SAASAPP5 = @SAASAPP5,
		 SAASAPP6 = @SAASAPP6,

		 HCCBFAT = @HCCBFAT,
		 HCCBUAT = @HCCBUAT,
		 TRAINING = @TRAINING,
		 
		 SAASSIT = @SAASSIT,
		 SAASUAT = @SAASUAT,
		 SAASPILOT = @SAASPILOT,
		 SAASDEMO = @SAASDEMO,

		 SITV2APP = @SITV2APP,
		 UATV2APP = @UATV2APP,
		 PRDV2APP1 = @PRDV2APP1,
		 
		 DEMOV2 = @DEMOV2,
		 
		 IsActive= CASE @IsActive WHEN 'Active' THEN '1' ELSE '0' END
	FROM Consumers C
	INNER JOIN ServerMaster SM WITH(NOLOCK) ON C.ServerID = sm.ID
	INNER JOIN Applications A WITH(NOLOCK) ON C.ApplicationID = A.ID
	WHERE SM.ServerName = @Server
	AND A.ApplicationName = @Application
END


      

