name: XPDEPLOY-Build

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2019  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3
      
    - name: Build Application
      run: msbuild xpdeploy.sln


  
