name: XPDEPLOY-Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3 
      
    - name: Navigate to Workspace12
      run: cd $GITHUB_WORKSPACE
      
    - name: Create Build Directory
      run: mkdir buildapp
      
    - name: Build app for release L
      run: msbuild xpdeploy.sln -t:rebuild -verbosity:diag -property:Configuration=Release
  
    - name: Build List
      run: |
        cd PrecompiledWeb\release
        powershell Get-ChildItem

