name: Build
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
        
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: |
        # powershell Get-Package *Sonar*
        # msbuild xpdeploy.sln -t:rebuild -verbosity:diag -property:Configuration=Release
        # powershell Get-ChildItem
        # cd PrecompiledWeb\release
        powershell Get-ChildItem

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
        SonarScanner.MSBuild.exe begin /k:"Satheesh1128_xpdeploy" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        MSBuild.exe xpdeploy.sln /t:Rebuild
        SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
